/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
println("=== Etapa 1: Funciones Básicas ===")
// TODO: Implementar función calcularPromedio
val promedio1 = calcularPromedio(7.5, 8.0)
println("El promedio es: $promedio1")

// TODO: Implementar función esAprobado
val nota = 7.0
val aprobado = esAprobado(nota)
println("¿Está aprobado? $aprobado")
}

// TODO: Implementar las siguientes funciones:

// Etapa 1
fun calcularPromedio(nota1: Double, nota2: Double): Double {
// Implementar aquí
return (nota1 + nota2) / 2
}

fun esAprobado(nota: Double): Boolean {
// Implementar aquí
return nota >= 6.0
}

